export declare function insertGroupReadCursor(cursorJSON: string): Promise<string>;
export declare function getGroupReadCursor(conversationID: string, userID: string): Promise<string>;
export declare function getGroupReadCursorsByConversationID(conversationID: string): Promise<string>;
export declare function updateGroupReadCursor(conversationID: string, userID: string, maxReadSeq: number): Promise<string>;
export declare function deleteGroupReadCursor(conversationID: string, userID: string): Promise<string>;
export declare function deleteGroupReadCursorsByConversationID(conversationID: string): Promise<string>;
export declare function upsertGroupReadCursor(cursorJSON: string): Promise<string>;
export declare function getMinReadSeqFromCursors(conversationID: string): Promise<string>;
export declare function getGroupReadState(conversationID: string): Promise<string>;
export declare function upsertGroupReadState(stateJSON: string): Promise<string>;
export declare function updateGroupReadStateMinSeq(conversationID: string, minReadSeq: number): Promise<string>;
export declare function deleteGroupReadState(conversationID: string): Promise<string>;
